
const obsPoints=["Opdagede selv situationen","Gik hen til barnet","Skabte kontakt til barnet","Forsøgte at forstå barnets ønske eller behov","Satte enkle ord på situationen","Viste barnet en anden handlemulighed","Kunne bagefter fortælle, hvad der skete","Kunne forklare, hvorfor hun gjorde, som hun gjorde"];
const supportLevels=["Selvstændigt","Efter kort påmindelse","Efter konkret instruktion","Ikke udført","Vejleder greb ind af hensyn til barnet"];
let activePin="",records=[],legacyRecords=[];
function buildObs(){const root=document.getElementById("observations");root.innerHTML="";obsPoints.forEach((p,i)=>{const d=document.createElement("div");d.className="obs";d.innerHTML=`<div class="obs-title">${i+1}. ${escapeHtml(p)}</div><div class="support-grid">${supportLevels.map(v=>`<label><input type="radio" name="obs${i}" value="${escapeHtml(v)}"> ${escapeHtml(v)}</label>`).join("")}</div>`;root.appendChild(d)})}
function toggleTransfer(){const active=document.getElementById("day").value!=="Mandag",box=document.getElementById("transferSection");box.classList.toggle("inactive",!active);box.querySelectorAll("input,textarea,select").forEach(el=>el.disabled=!active)}
async function deriveKey(pin,salt){const enc=new TextEncoder(),material=await crypto.subtle.importKey("raw",enc.encode(pin),{name:"PBKDF2"},false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:150000,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function b64(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes)))}function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function encryptJson(obj,pin){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(pin,salt),data=new TextEncoder().encode(JSON.stringify(obj)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,data);return{salt:b64(salt),iv:b64(iv),cipher:b64(cipher)}}
async function decryptJson(payload,pin){const key=await deriveKey(pin,unb64(payload.salt)),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(payload.iv)},key,unb64(payload.cipher));return JSON.parse(new TextDecoder().decode(plain))}
async function pinVerifier(pin){return b64(await crypto.subtle.digest("SHA-256",new TextEncoder().encode("PAU:"+pin)))}
async function unlock(){const pin=document.getElementById("pin").value.trim(),msg=document.getElementById("lockMessage");if(pin.length<4){msg.textContent="Koden skal være mindst fire tegn.";return}const stored=localStorage.getItem("pau_pin_verifier"),verify=await pinVerifier(pin);if(!stored)localStorage.setItem("pau_pin_verifier",verify);else if(stored!==verify){msg.textContent="Forkert kode.";return}activePin=pin;document.getElementById("lockScreen").classList.add("hidden");document.getElementById("advisorApp").classList.remove("hidden");await loadAllRecords()}
function lockNow(){activePin="";document.getElementById("pin").value="";document.getElementById("advisorApp").classList.add("hidden");document.getElementById("lockScreen").classList.remove("hidden")}
async function migrateLegacy(){const oldRaw=localStorage.getItem("pau_advisor_records_encrypted");if(!oldRaw||localStorage.getItem("pau_legacy_migrated")==="yes")return;try{const old=await decryptJson(JSON.parse(oldRaw),activePin);legacyRecords=Array.isArray(old)?old:[];localStorage.setItem("pau_advisor_legacy_encrypted",JSON.stringify(await encryptJson(legacyRecords,activePin)));localStorage.setItem("pau_legacy_migrated","yes")}catch(e){}}
async function loadAllRecords(){await migrateLegacy();records=[];legacyRecords=[];const raw=localStorage.getItem("pau_advisor_v12_encrypted");if(raw){try{records=await decryptJson(JSON.parse(raw),activePin)}catch(e){}}const legacyRaw=localStorage.getItem("pau_advisor_legacy_encrypted");if(legacyRaw){try{legacyRecords=await decryptJson(JSON.parse(legacyRaw),activePin)}catch(e){}}renderHistory();renderLegacyHistory();if(records.length)renderSummary(records[records.length-1])}
async function saveAdvisor(){const observations=obsPoints.map((p,i)=>{const x=document.querySelector(`input[name="obs${i}"]:checked`);return{point:p,support:x?x.value:"Ikke registreret"}}),day=document.getElementById("day").value,t=day!=="Mandag"?{date:document.getElementById("transferDate").value,situation:document.getElementById("transferSituation").value.trim(),action:document.getElementById("transferAction").value.trim(),support:document.getElementById("transferSupport").value}:null,hasTransfer=t&&(t.date||t.situation||t.action||t.support),data={schemaVersion:"1.2",id:crypto.randomUUID(),date:new Date().toISOString(),day,studentId:document.getElementById("studentId").value.trim().slice(0,12),place:document.getElementById("place").value,childInitial:document.getElementById("initial").value.trim().slice(0,2),observations,promptText:document.getElementById("promptText").value.trim(),tellSummary:document.getElementById("tellSummary").value.trim(),transfer:hasTransfer?t:null};records.push(data);localStorage.setItem("pau_advisor_v12_encrypted",JSON.stringify(await encryptJson(records,activePin)));alert("Registreringen er gemt krypteret.");renderSummary(data);renderHistory()}
function showLatestStatus(){records.length?renderSummary(records[records.length-1]):document.getElementById("summary").textContent="Der er endnu ikke gemt en registrering."}
function renderSummary(data){if(!data){document.getElementById("summary").textContent="Der er endnu ikke gemt en registrering.";return}const transfer=data.transfer?`<h3>Overførsel til en ny situation</h3><p><strong>Dato:</strong> ${escapeHtml(data.transfer.date||"Ikke angivet")}</p><p><strong>Ny situation:</strong><br>${nl2br(data.transfer.situation||"Ikke angivet")}</p><p><strong>Elevens konkrete handling:</strong><br>${nl2br(data.transfer.action||"Ikke angivet")}</p><p><strong>Støtteniveau:</strong> ${escapeHtml(data.transfer.support||"Ikke angivet")}</p>`:`<h3>Overførsel til en ny situation</h3><p>Ikke observeret eller ikke registreret.</p>`;document.getElementById("summary").innerHTML=`<p><strong>${escapeHtml(data.day)}</strong> · ${new Date(data.date).toLocaleString("da-DK")}</p><p><strong>Elev-id:</strong> ${escapeHtml(data.studentId||"Ikke angivet")}</p><p><strong>Sted:</strong> ${escapeHtml(data.place||"Ikke angivet")}</p><p><strong>Barnets forbogstav:</strong> ${escapeHtml(data.childInitial||"Ikke angivet")}</p><h3>Handlinger og støtte</h3><ol>${data.observations.map(o=>`<li><strong>${escapeHtml(o.point)}:</strong> ${escapeHtml(o.support)}</li>`).join("")}</ol><p><strong>Hvad sagde vejlederen ved påmindelse eller instruktion?</strong><br>${nl2br(data.promptText||"Ikke angivet")}</p><p><strong>Kort referat af Fortæl-samtalen</strong><br>${nl2br(data.tellSummary||"Ikke angivet")}</p>${transfer}`}
function renderHistory(){const el=document.getElementById("history");if(!records.length){el.textContent="Ingen registreringer.";return}el.innerHTML=records.map((r,i)=>`<div class="record-card"><strong>${i+1}. ${escapeHtml(r.day)}</strong> · ${new Date(r.date).toLocaleString("da-DK")} · ${escapeHtml(r.studentId||"uden elev-id")}<div class="actions no-print"><button class="secondary" onclick="renderSummary(records[${i}])">Vis registrering</button></div></div>`).join("")}
function renderLegacyHistory(){const el=document.getElementById("legacyHistory");if(!legacyRecords.length){el.textContent="Ingen ældre registreringer.";return}el.innerHTML=legacyRecords.map((r,i)=>`<div class="legacy"><strong>Version 1.1 · ${escapeHtml(r.day||"Dag ikke angivet")}</strong> · ${r.date?new Date(r.date).toLocaleString("da-DK"):"Dato ikke angivet"}<div class="actions no-print"><button class="secondary" onclick="showLegacy(${i})">Vis ældre registrering</button></div></div>`).join("")}
function showLegacy(i){const r=legacyRecords[i];if(!r)return;document.getElementById("summary").innerHTML=`<div class="legacy"><strong>Ældre registrering · version 1.1</strong></div><p><strong>${escapeHtml(r.day||"Dag ikke angivet")}</strong> · ${r.date?new Date(r.date).toLocaleString("da-DK"):"Dato ikke angivet"}</p><p><strong>Elev-id:</strong> ${escapeHtml(r.studentId||"Ikke angivet")}</p><p><strong>Sted:</strong> ${escapeHtml(r.place||"Ikke angivet")}</p><p><strong>Barnets forbogstav:</strong> ${escapeHtml(r.childInitial||"Ikke angivet")}</p><h3>Handlinger og støtte</h3><ol>${(r.observations||[]).map(o=>`<li><strong>${escapeHtml(o.point||"")}</strong>: ${escapeHtml(o.support||"")}</li>`).join("")}</ol><p><strong>Vejlederens ord:</strong><br>${nl2br(r.promptText||"Ikke angivet")}</p><p><strong>Referat af Fortæl-samtalen:</strong><br>${nl2br(r.tellSummary||"Ikke angivet")}</p>`}
function renderComparison(){const el=document.getElementById("comparison");if(records.length<2){el.textContent="Der skal være mindst to version 1.2-registreringer for at sammenligne.";return}let html="<table><thead><tr><th>Observation</th>"+records.map(r=>`<th>${escapeHtml(r.day)}</th>`).join("")+"</tr></thead><tbody>";obsPoints.forEach((p,idx)=>{html+=`<tr><td>${escapeHtml(p)}</td>`;records.forEach(r=>html+=`<td>${escapeHtml(r.observations[idx]?.support||"Ikke registreret")}</td>`);html+="</tr>"});el.innerHTML=html+"</tbody></table>"}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function nl2br(s){return escapeHtml(s).replace(/\n/g,"<br>")}
function resetAdvisor(){if(confirm("Vil du slette alle vejlederdata og den lokale kode fra denne enhed?")){["pau_advisor_v12_encrypted","pau_advisor_legacy_encrypted","pau_advisor_records_encrypted","pau_pin_verifier","pau_legacy_migrated"].forEach(k=>localStorage.removeItem(k));location.reload()}}
buildObs();toggleTransfer();
